services:
  web:
    image: ghcr.io/mupinnn/todo-docker/web:${IMAGE_TAG:-latest}
    env_file: apps/web/.env
    ports:
      - "127.0.0.1:5173:80"
    depends_on:
      - api
    restart: unless-stopped

  migrate:
    image: ghcr.io/mupinnn/todo-docker/migrate:${IMAGE_TAG:-latest}
    env_file: apps/api/.env
    depends_on:
      - db
    restart: "no"

  api:
    image: ghcr.io/mupinnn/todo-docker/api:${IMAGE_TAG:-latest}
    ports:
      - "127.0.0.1:3000:3000"
    env_file: apps/api/.env
    depends_on:
      migrate:
        condition: service_completed_successfully
      db:
        condition: service_started
    restart: unless-stopped

  db:
    ports: !override
      - "127.0.0.1:5432:5432"
