name: E2E tests on PR

on:
  workflow_run:
    workflows: ["Build Docker Image on PR"]
    types: ["completed"]

env:
  REGISTRY: ghcr.io

jobs:
  e2e:
    if: >
      github.event.workflow_run.event == 'pull_request' && 
      github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run E2E tests
        env:
          API_IMAGE: ${{ env.REGISTRY }}/${{ github.repository }}-web:pr-${{ github.event.pull_request.number }}
          WEB_IMAGE: ${{ env.REGISTRY}}/${{ github.repository }}-api:pr-${{ github.event.pull_request.number }}
          MIGRATE_IMAGE: ${{ env.REGISTRY }}/${{ github.repository }}-migrate:pr-${{ github.event.pull_request.number }}
        run: |
          cat <<EOF > docker-compose.e2e.run.yml
          services:
            db:
              image: postgres:16
              environment:
                - POSTGRES_PASSWORD=postgres
                - POSTGRES_USER=postgres
                - POSTGRES_DB=postgres
            migrate:
              image: ${MIGRATE_IMAGE}
              environment:
                - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
              depends_on:
                db:
                  condition: service_started
            api:
              image: ${API_IMAGE}
              environment:
                - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
              depends_on:
                migrate:
                  condition: service_completed_successfully
                db:
                  condition: service_started
            web:
              image: ${WEB_IMAGE}
              depends_on:
                - api
            playwright:
              image: mcr.microsoft.com/playwright:v1.49.1-jammy
              environment:
                - BASE_URL=http://web:80
              working_dir: /app/e2e
              volumes:
                - .:/app
              command: npx playwright test
              depends_on:
                web:
                  condition: service_started
          EOF

          docker compose -f docker-compose.e2e.run.yml up --exit-code-from playwright
